---
- name: Join node to Kubernetes master
  shell: >
    {{ kubernetes_join_command }}
    {{ kubernetes_join_command_extra_opts }}
#    --config={{ kubeadm_crio_config }}
  creates: /etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']
